# Generated by Django 5.1.1 on 2024-10-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Unkown', max_length=33)),
                ('last_name', models.CharField(default='Unkown', max_length=33)),
                ('age', models.PositiveIntegerField(default=18)),
                ('image', models.ImageField(null=True, upload_to='Doctors/images/%y/%m/%d')),
                ('file_report', models.FileField(null=True, upload_to='Doctors/files/%y/%m/%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('report', models.TextField(max_length=200)),
            ],
        ),
    ]
