# Generated by Django 5.1.1 on 2024-11-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='mattress',
            field=models.CharField(default='UnKnown', max_length=12),
        ),
        migrations.AddField(
            model_name='doctors',
            name='specialization',
            field=models.CharField(default='UnKnown', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=33),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=33),
        ),
    ]
